[build]
  publish = "docs"
  command = "cd frontend/meeting-summarizer && npm run build && cp -r dist/* ../../docs/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend/meeting-summarizer && npm run dev"
  port = 5173